[package]
name        = "cosaci-protocol"
version.workspace    = true
edition.workspace    = true
license.workspace    = true
repository.workspace = true
authors.workspace    = true
description = "CosaCI: wire protocol (CBOR envelopes) + mTLS transport (rustls)"
readme      = "../../README.md"
keywords    = ["distributed", "ci", "mtls", "rustls", "cbor"]
categories  = ["network-programming", "encoding"]
publish     = false

[dependencies]
cosaci-core     = { path = "../cosaci-core" }
ciborium        = { workspace = true }
rcgen           = { workspace = true }
rustls          = { workspace = true }
rustls-pemfile  = { workspace = true }
serde           = { workspace = true }
serde-big-array = { workspace = true }
time            = { workspace = true }

[lints]
workspace = true
